apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cvb-production

resources:
  - deployment.yaml
  - ingress.yaml

images:
  - name: ghcr.io/raphaelrbrt/ptf-front
    newTag: main

commonLabels:
  app: ptf-front
  environment: production